### ISSUE TITLE
License for Zhengma table

### ISSUE THREAD

**Issue by SRGOM** [heiher/ibus-table-zhengma#1]
I have a question if you can answer about this. Do you have any pointers about where can I get licensing information for this? I will be using Zhengma input method to type documents that may directly earn me money. I emailed zhongyi@263.net but didn't get any response there.

**Comment by heiher** [comment]
GPL-3

**Comment by SRGOM** [comment]
@@Thanks for responding. But isn't Zhengma a propreitary system of zhongyi (which they sued Microsoft for)? 

I'm assuming you're referring to your work, not the actual Zhengma system... Is that so?
