### ISSUE TITLE
Consider undoing the removal of 49,000 characters

### ISSUE THREAD

**Issue by Serentty** [heiher/ibus-table-zhengma#2]
I use Zhengma because it is the only convenient way to type very rare Chinese characters that aren't in most IME dictionaries. I install very comprehensive Unicode fonts so that I can see these characters. So, the removal of these rare characters that aren't covered by Source Han Sans makes it harder for me to input these rare, obscure, and ancient characters.

**Comment by heiher** [comment]
Hmm, I think you can fork and revert it. :)
